### ISSUE TITLE
[1.12] Some Pets are not working

### ISSUE THREAD

**Issue by i9hdkill** [TechzoneMC/SonarPet#102]
The following pets are not working after a quick test:

- slime
- magmacube
- silverfish
- wither
- zombie
- ocelot

And eventually more.
Except for ocelots, they just don't spawn.
No errors. Only get an error when spawning an ocelot pet:
https://pastebin.com/REXjU1bB
I know that parrots somehow are based on ocelots , as they are both tameable. Maybe this causes that.

**Comment by Techcable** [comment]
Fixed the issue with ocelot pets, which also affected any other pets with colored (like wolves or sheep).
Strangely after I fixed some other issues I was unable to reproduce the issue with non-ocelot pets.
