### ISSUE TITLE
parrots are dead

### ISSUE THREAD

**Issue by PhanaticD** [TechzoneMC/SonarPet#113]
parrots dont move on 1.12, pretty easy to reproduce just do /pet parrot and watch it not do anything

**Comment by PhanaticD** [comment]
cant right click it either

**Comment by silencercomes** [comment]
just a quick fix/workaround: in the config enable that parrots can fly. 
it is currently set to false, so the parrot keeps sitting and does not fly to you.

**Comment by Techcable** [comment]
This was a fascinating bug but I think I fixed it in ebdecd7 (alongside several other movement problems). Thanks for the hint @silencercomes , turns out it was a problem with the navigation code.
