### ISSUE TITLE
Creating pet issue still exists.

### ISSUE THREAD

**Issue by CharlieIsHere** [TechzoneMC/SonarPet#13]
https://gist.github.com/CharlieIsHere/d70911d062b5f32bd572

Hey, I know you said it was fixed in the new push, but its still not fixed :(

**Comment by Techcable** [comment]
Are there any other errors in the log?

**Comment by CharlieIsHere** [comment]
There are no other errors, sorry for opening a new ticket instead of re-opening the old one.

**Comment by Techcable** [comment]
Its fine :)

**Comment by CharlieIsHere** [comment]
Hey Techcable, don't mean to pester you but is there an update on this bug?

**Comment by Techcable** [comment]
Any errors on startup? A NoClassDefFoundError usually has a cause.

**Comment by andrewkm** [comment]
I cannot reproduce this issue.
Creating pets works perfectly fine for us here.

Please show startup logs @CharlieIsHere including any errors that may or may not be showing up on pet creation.

Using Spigot 800 and SonarPet 15

**Comment by CharlieIsHere** [comment]
Yeah now it says this: https://gist.github.com/CharlieIsHere/34ca9b3ff7b06d322523d6a660cebd01

**Comment by andrewkm** [comment]
I cannot reproduce this. Make sure you're using latest version of everything.

**Comment by CharlieIsHere** [comment]
Sure just in case there were jar mixes ill get all new jars and try again.

**Comment by CharlieIsHere** [comment]
It happens when I do these commands:
/pet sheep
/pet sheep Sheeper

**Comment by CharlieIsHere** [comment]
Yeah its still working guys.
