### ISSUE TITLE
Notifies you of updates for the old echopet

### ISSUE THREAD

**Issue by Techcable** [TechzoneMC/SonarPet#15]
The thingy checks bukit dev for echopet updates, and it tells the user its running an 'old version'.

**Comment by Fridgey** [comment]
Still tells the user to update.

**Comment by Internetpilot** [comment]
I think you're still encountering this issue because you're using an old version of the plugin.  I haven't been getting this for several versions now.

**Comment by Fridgey** [comment]
I downloaded it straight from here? is this not the most updated?

**Comment by Internetpilot** [comment]
I've always downloaded it from Jenkins.  I think it's on Build #14 now with a lot of the initial issues fixed.  I would guess it's at least 99% working now.  I'm currently using other plugins that have far more issues with 1.9 than this plugin.

https://ci.techcable.net/job/SonarPets/

**Comment by Techcable** [comment]
Yes, it has most issues fixed in the development builds ;)
