### ISSUE TITLE
Permissions and errors

### ISSUE THREAD

**Issue by Cleggy1012** [TechzoneMC/SonarPet#16]
http://pastebin.com/GphH7bPa

~~There is also a issue where players can't ride or use hats when they have~~
~~echopet.pet.ride.*~~
~~echopet.pet.hat.*~~

~~And not being able to select different types of pet's when they have~~
~~echopet.pet.type.{type}.*~~

**Comment by Techcable** [comment]
Please file multiple issues when you have multiple issues.
your second and 3rd issues are duplicates of the various riding issues.
