### ISSUE TITLE
All the spawn eggs are the same

### ISSUE THREAD

**Issue by Internetpilot** [TechzoneMC/SonarPet#2]
In the pet selector menu all the spawn eggs are the same (except for the Ender Dragon, Iron Golem, Human, Wither, and Snowman.  It doesn't seem to be passing on the materialdata designated in the config.yml so all of them are just displayed as materialID 383.

**Comment by afaik4711** [comment]
+1 on that. Please add the new materialnames for the eggs or add support for player heads (eg: MHF_Pig)
Thanks a dozen.

**Comment by Internetpilot** [comment]
In Build #13 all the spawn eggs are still the same even after I delete config.yml and let it regenerate when rebooting the server.

**Comment by andrewkm** [comment]
Can confirm, build 15 all the spawn eggs are exactly the same.
