### ISSUE TITLE
Build #15 Pet Hat Crashes Java Binary

### ISSUE THREAD

**Issue by Internetpilot** [TechzoneMC/SonarPet#20]
With Build #15 attempting to switch out of the Pet Hat feature causes the Java binary to crash on the client (not the server).  There is no console message or error message in Minecraft other than reporting the Java binary has stopped responding.  If you toggle the pet instead of switching off the Pet Hat feature, the problem doesn't occur.

**Comment by Techcable** [comment]
Can you get me logs from the client _and_ the server?
What version of minecraft and java are you using?

**Comment by Techcable** [comment]
Hats work just fine for me on TacoSpigot 1.9 with a forge 1.9 client.
![Horse hat](https://i.gyazo.com/00c0ef6dff7e8c52b36b29824d724f40.png)

**Comment by Internetpilot** [comment]
I'm using the latest build (as of today, 4/11/16) of Spigot 1.9.2, the latest vanilla Minecraft client (1.9.2), and I have no idea what version of Java I'm running on the client because I've never installed it on this gaming laptop (it's brand new) so it must just be whatever the Minecraft client installs/downloads.  

There's nothing in either the Spigot logs or the Minecraft client logs. I don't know where I would find any Java client logs since I never actually installed Java on this laptop???

The pet hat feature definitely works for me, too.  But when I click on the pet hat icon again (which is supposed to remove the pet from your head), that's when Java crashes. If I just toggle the pet off instead of attempting to remove the pet from my head with the pet hat icon, it doesn't crash.

**Comment by andrewkm** [comment]
Using Spigot 800, SonarPets 15.
Client Using 1.9.2 with Forge and WorldEdit CUI.

Cannot reproduce this issue at all and am not experiencing any crashing.

**Comment by Internetpilot** [comment]
I can reproduce this exact error on all seven PCs that I have in this house running the latest Minecraft client (which have either Java 8 Update 77 manually installed or whatever is automatically installed with Minecraft these days).  I'm running the latest build of a self-hosted Spigot 1.9.2 server (also with Java 8 Update 77).  So far, four of my users are also encountering the exact same issue.  I have no idea what Java version they're running (because neither do they -- haha).  

To definitely reproduce the problem every time, activate the pet hat feature and then directly activate the ride your pet feature.  It always causes the Java SE to stop responding, locking up the Minecraft client.  Sometimes if you activate the pet hat feature and then press the pet hat feature again (like to take the pet off your head) it will also lock up, but not every time -- probably about 75% of the time.  

The Spigot server is unaffected with nothing noted in the console log, even if I run the Minecraft client on that server (remember, I'm self-hosted).  There's nothing noted in the Minecraft client log either.  Seems to be a 100% Java issue like a bad programming call or something.

**Comment by Techcable** [comment]
Yes, but what errors show up on the client?

**Comment by Internetpilot** [comment]
It's simply says that Java SE had stopped responding and asks if you want to close it. If you do, Minecraft closes if you don't it just stays locked up. There are no other messages or errors.

**Comment by Techcable** [comment]
No I mean what are the contents of the debug log?
You go into profile settings and set the launcher visibility options to 'Keep the launcher open'.
Then you should see the launcher stay open showing debug logs.
Once the client crashes, the launcher should stay open (they're seperate processes). Then right click on the logs, click 'Copy All Text', and paste it into a [github gist](https://gist.github.com/) (the logs may be very large, and github gist is probably one of the best pasting services).

**Comment by Internetpilot** [comment]
There is nothing there. It's not the Minecraft client that's was crashing. Java SE is. It doesn't happen anymore with the latest build (#17).

**Comment by Techcable** [comment]
Okay, so I guess this is fixed :tada:

**Comment by Internetpilot** [comment]
Aren't those the very best kind of issues?  :smile:
