### ISSUE TITLE
Pet rider is completely broken.

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#22]
Pet rider is completely broken.
Just making this ticket as a place holder for the issue.

I see according to the thread you are already aware of this.

Spigot 800 SonarPets 15

**Comment by Techcable** [comment]
Really? I thought I fixed it in build 15.
How doesn't it work?

**Comment by andrewkm** [comment]
You are absolutely correct, my testing environment must have been out of date in some aspect.
Can confirm via production this issue is fixed.

Closing ticket.
