### ISSUE TITLE
Pets + 1.9 Boats

### ISSUE THREAD

**Issue by JamieSinn** [TechzoneMC/SonarPet#28]
#### Brief Description:
So I had my pet on and it decided to get in a boat that was at spawn (I have no idea how the boats got to spawn lol) and apparently once it got in the boat, it wouldn't disappear when I typed /pet toggle or /pet hide and even stayed there when I re logged. 
#### Instructions:
Spawn a pet in, and walk near a boat and it'll get into the boat. Then spawn more pets in and they can keep getting in boats without you being able to get rid of the boats or pets.
I tried re logging and I couldn't see the pets when I logged back on, however my alt was at spawn and could still see the pets in the boats even when I was offline and logged back on.
#### How many times did you recreate this bug?:
Like 10 times.
#### Result:
Pets everywhere that you can't remove via the /pet hide command. 
#### Expected Result:
For the /pet hide to remove the pets, and for pets not to steal the boats :p
#### Evidence:
![​IMG](https://www.ecocitycraft.com/forum/proxy.php?image=http%3A%2F%2Fi.imgur.com%2F65EvbWQ.jpg&hash=681950710f9314140f3455664b69d4f6)
Screenshot from my alts perspective after my main had re logged, so the the pets should have disappeared:
![​IMG](https://www.ecocitycraft.com/forum/proxy.php?image=http%3A%2F%2Fi.imgur.com%2FnJGzZ8k.jpg&hash=eaad3ef3ec6521a7c2ea8650e90e0e61)

**Comment by andrewkm** [comment]
Can confirm.

**Comment by Techcable** [comment]
For some reason horses don't have this issue

**Comment by Techcable** [comment]
Thanks for the detailed report :)
Before I fix this, I just want to say this issue is halarious

**Comment by JamieSinn** [comment]
Oh, I totally agree. It's quite hysterical.

**Comment by andrewkm** [comment]
WHY TECH WHY! What do you have against animals in boats!
(PS: thanks for fixing <3)
