### ISSUE TITLE
Build #9 v1.0.1 Riding Issues...

### ISSUE THREAD

**Issue by Internetpilot** [TechzoneMC/SonarPet#3]
Mounting them for riding definitely works now, but now I can no longer reliably control any of the pets when riding them. I cannot move forward or backward at all and can only jump in place.

Console errors:

`[22:19:27] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SonarPet v1.0.1-SNAPSHOT org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1852) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73] at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73] at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-f04e043-622014a] at java.lang.Thread.run(Unknown Source) [?:1.8.0_73] Caused by: org.bukkit.command.CommandException: Unhandled exception executing 'pet wither' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet) at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more Caused by: com.dsh105.echopet.compat.api.registration.PetRegistrationException: java.lang.IllegalStateException: Failed to create pet object for InternetPilot at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:121) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?] at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more Caused by: java.lang.IllegalStateException: Failed to create pet object for InternetPilot at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:85) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?] at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73] at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?] at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for InternetPilot at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:99) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:49) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:35) ~[?:?] at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:72) ~[?:?] at com.dsh105.echopet.api.pet.type.WitherPet.<init>(WitherPet.java:33) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73] at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?] at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73] at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:91) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:49) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:35) ~[?:?] at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:72) ~[?:?] at com.dsh105.echopet.api.pet.type.WitherPet.<init>(WitherPet.java:33) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73] at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?] at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more Caused by: java.lang.IllegalArgumentException: Duplicate id value for 13! at net.minecraft.server.v1_9_R1.DataWatcher.register(DataWatcher.java:63) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.nms.v1_9_R1.metadata.WrappedDataWatcher.register(WrappedDataWatcher.java:31) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.entity.type.EntityWitherPet.initDatawatcher(EntityWitherPet.java:58) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.entity.EntityPet.i(EntityPet.java:511) ~[?:?] at net.minecraft.server.v1_9_R1.Entity.<init>(Entity.java:184) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.EntityLiving.<init>(EntityLiving.java:120) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.EntityInsentient.<init>(EntityInsentient.java:48) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at net.minecraft.server.v1_9_R1.EntityCreature.<init>(EntityCreature.java:20) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.nms.v1_9_R1.entity.EntityPet.<init>(EntityPet.java:107) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.entity.type.EntityWitherPet.<init>(EntityWitherPet.java:43) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73] at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:91) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:142) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:49) ~[?:?] at com.dsh105.echopet.compat.nms.v1_9_R1.NMSImpl.spawn(NMSImpl.java:35) ~[?:?] at com.dsh105.echopet.api.pet.Pet.<init>(Pet.java:72) ~[?:?] at com.dsh105.echopet.api.pet.type.WitherPet.<init>(WitherPet.java:33) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73] at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createFor(PetRegistrationEntry.java:77) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:105) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry$1.call(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.performRegistration(PetRegistry.java:119) ~[?:?] at com.dsh105.echopet.compat.api.registration.PetRegistry.spawn(PetRegistry.java:102) ~[?:?] at com.dsh105.echopet.compat.api.entity.PetType.getNewPetInstance(PetType.java:147) ~[?:?] at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:121) ~[?:?] at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:411) ~[?:?] at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] at com.dsh105.echopet.compat.api.util.menu.SelectorIcon.onClick(SelectorIcon.java:77) ~[?:?] at com.dsh105.echopet.compat.api.util.inventory.InventoryMenu.onInvClick(InventoryMenu.java:97) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-f04e043-622014a] ... 15 more `

**Comment by Techcable** [comment]
I can't read your error :(

**Comment by Techcable** [comment]
a22f9d93f6f6087bfc498e3de3db8fc63b43218f (build 10) fixes your issue.
