### ISSUE TITLE
Stacking pets increases the speed they follow you at.

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#30]
Extensive bug report here:
https://www.ecocitycraft.com/forum/threads/bug-report-speed-10-pets.148741/

Video here:
https://www.youtube.com/watch?time_continue=18&v=nu7-XORE68s

**Comment by JamieSinn** [comment]
Can confirm. Yet another funny issue.

**Comment by Techcable** [comment]
Appears to be fixed as of the refractor ([build 23](https://ci.techcable.net/job/SonarPets/23/)).
Re-open if its still happening.
