### ISSUE TITLE
Reload doesn't update prefix

### ISSUE THREAD

**Issue by SioWolf** [TechzoneMC/SonarPet#31]
When I try to change the prefix in the language file it is still the default [SonarPets] ingame. I can see that all the other messages have changed, but the prefix seems to be ignored.

**Comment by Techcable** [comment]
What prefix isn't changed?
I don't see anything hardcoded.

**Comment by andrewkm** [comment]
Cannot reproduce:

http://i.imgur.com/wdz0E67.png
Not a bug.

Please post your language file so we may see what you might be doing wrong.

**Comment by SioWolf** [comment]
It appears to be working now, which is odd.

After changing the color codes and prefix, and doing /petadmin reload, the new color codes were working in chat but the old prefix remained.

Now after a server reboot the prefix is gone and everything is working.

It seems that /petadmin reload doesn't update the prefix? I haven't touched anything since I posted this and the automatic server reboot fixed it.

**Comment by andrewkm** [comment]
@Techable can confirm, /petadmin reload does not update language file.
In my opinion not really a major issue, but perhaps a low priority future enchancement.

**Comment by Techcable** [comment]
Re-open (or comment) if not fixed.
