### ISSUE TITLE
Pet Select - Lag Spike

### ISSUE THREAD

**Issue by BiGUNMAN** [TechzoneMC/SonarPet#32]
Hi, when one uses /pet select a massive lag spike occurs. I use MassiveLag so here's a pastebin of what it reports: http://pastebin.com/tFWnDeA3 (The issue is not related to DeluxeCommands for anyone which thinks "it might be a cause".

**Comment by Techcable** [comment]
Odd, it shouldn't do a uuid lookup if the players aren't online.
It says 'children hidden', can you expand that?

**Comment by BiGUNMAN** [comment]
Well, I'm now using Paper so I've removed MassiveLag, I'll see what I can get from a timings report.
