### ISSUE TITLE
Cannot edit rider pets in the Pet DataMenu (right clicking a pet)

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#34]
An old issue back from the EchoPet days:
https://www.ecocitycraft.com/forum/threads/bug-report-change-rider-pets.98815/

According to our users the issue still exists:
https://www.ecocitycraft.com/forum/threads/bug-report-change-rider-pets.98815/#post-827101

Please advise.

**Comment by Techcable** [comment]
Difficult since rider pets are so crazy and special-case :/

**Comment by andrewkm** [comment]
Fixed for me.
