### ISSUE TITLE
Horses moves in 1.9

### ISSUE THREAD

**Issue by FlorianFun** [TechzoneMC/SonarPet#37]
Due to 1.9, the moves of the horse when we ride them are now handled by the client. 

So, when we move, we don't see ourselves move, but the server understands that we move. I use a particle plugin that plays particles on the player, et the move accordingly to us.
Also, when we get off the horse, we are teleported to the location of the particles.

Riding a vanilla horse is not perturbated.
This only happens with horses.

Spigot version : git-Spigot-5a40365-b103841 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
SonarPet Version : 1.0.1

**Comment by Techcable** [comment]
Does it happen when a saddle is on?

**Comment by FlorianFun** [comment]
The behaviour with a saddle is different : the horse is now mush faster on the client than on the server. 
We see ourselves outstrip the particles and move very fast.

**Comment by Techcable** [comment]
What do you mean outstrip the particles?

**Comment by FlorianFun** [comment]
We get in front of them. We are faster than them. We see ourselves move at, let's say 5blocks/s (for example), and the particle move at 2blocks/s.
We don't move in the same way on the client and the server.

**Comment by Techcable** [comment]
So other players see you move differently?

**Comment by FlorianFun** [comment]
Yes, other players see us move like the server does; they see us normally, and on the particles.

**Comment by Techcable** [comment]
So the client thinks its moving extra fast?
Does this hapen with NoCheatPlus installed?

**Comment by FlorianFun** [comment]
I didn't try NoCheatPlus. I'll try it tonight or tomorrow.
Thought, I'm pretty sure this is linked to the new way horses are handled with 1.9.

> Riding entities such as boats, horses, minecarts and saddled pigs, are now run by the client instead by the server.
http://minecraft.gamepedia.com/1.9
