### ISSUE TITLE
Shutdown method deprecated.

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#38]
While stopping server, I get the following just after SonarPet:

2016-04-29 09:18:29 [INFO] [SonarPet] Disabling SonarPet v1.0.1
2016-04-29 09:18:29 [WARN] The shutdown() method has been deprecated, please use the close() method instead

**Comment by kukelekuuk00** [comment]
https://github.com/brettwooldridge/HikariCP/blob/0e08531a23f8ce619f27ca0f425d2b5a647ae926/src/main/java/com/zaxxer/hikari/HikariDataSource.java#L331
https://github.com/TechzoneMC/SonarPet/blob/6d79ee0914cc6893e2a65435adb2d011c12a4586/modules/EchoPet/src/main/java/com/dsh105/echopet/EchoPetPlugin.java#L167
