### ISSUE TITLE
Pet remove doesn't remove them from your hat.

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#39]
https://www.ecocitycraft.com/forum/threads/bug-report-pet-remove-not-clearing-pet-hats.149702/

Brief Description: The command /pet remove does not clear all pets if you summon two at a time and then wear them using /pet hat.

Instructions:
1. Summon two pets via /pet spider creeper (or whatever pets you have)
2. Use the command /pet hat
3. Enjoy your fancy hat
4. Use the command /pet remove while wearing your hat
5. Only the second pet is removed, the first one you call remains as a hat
6. Try /pet remove again; it says you do not have any pets.
7. Stuck with pets as a hat until you relog.

How many times did you recreate this bug?: Every single time I tried. It's not just a client side visual glitch, I had people at mining spawn confirm they saw multiple pets on my head. D:

Result: Infinite pet hat party

Expected Result: /pet remove to remove all of your pets

Screenshot: https://i.gyazo.com/f98f6349dff0904a1ee6624dc2dfb300.png

**Comment by Techcable** [comment]
I think this is because we have to cancel all dismount requests because of 1.9 stupidity.
However, it may be a deeper problem then that.

**Comment by andrewkm** [comment]
Fixed for me.
