### ISSUE TITLE
spigot 1.8.8 - bat/sheep crashes server

### ISSUE THREAD

**Issue by i9hdkill** [TechzoneMC/SonarPet#42]
See title
This server is running CraftBukkit version git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[SonarPet] Loading SonarPet v1.0.2-SNAPSHOT
Latest commit:
https://github.com/TechzoneMC/SonarPet/commit/fb8a5f927f669522dcec2833469f26e0de854cdd
This commit might even broke it
http://pastebin.com/qsBDTqYy

**Comment by i9hdkill** [comment]
Same with sheep:
http://pastebin.com/ekWx2ZAX

**Comment by Techcable** [comment]
Can I see the full log?

**Comment by i9hdkill** [comment]
sheeplog:
http://pastebin.com/F7TKgNKV
sheepminecraftcrashlog:
http://pastebin.com/9qt51Dm4
batcrash:
http://pastebin.com/85EhZX3J
batminecraftcrashlog:
http://pastebin.com/Q6bzPc8W

**Comment by Techcable** [comment]
Just reopen/comment if this doesn't fix it.

**Comment by i9hdkill** [comment]
Does not fix the issue:/
http://pastebin.com/BGkinBVe
I used devbuild 19 for testing

**Comment by Techcable** [comment]
Should be fixed in [build 23](https://ci.techcable.net/job/SonarPets/23/)
