### ISSUE TITLE
Killed by 1.9.4

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#43]
http://pastie.org/pastes/10831311/text?key=4ptfdstyhzs4ph9euvtlnw

**Comment by Techcable** [comment]
I'll probably start on this after I update TacoSpigot to 1.9.4 (and therefore after @Zbob750 updates Paper), and after Tux and I finish the waterfall update to 1.9.4.

**Comment by cindyker** [comment]
:( cindy sady face

**Comment by andrewkm** [comment]
We'll update this in 1-2 days if Techcable doesn't have time as a temporary update Cindy.

**Comment by Internetpilot** [comment]
Internetpilot smiley face :)

**Comment by Techcable** [comment]
Untested update done in 5 minutes.
Report any and all bugs to your nearest SonarPets representative.

**Comment by andrewkm** [comment]
Not working.
http://i.imgur.com/hoO45Hf.png

We're currently using a build from @cindyker which works well. Maybe she can shed some light as to what's going on with this one. (I'm not a dev so don't know)

**Comment by andrewkm** [comment]
@Techcable https://github.com/TechzoneMC/SonarPet/blob/master/modules/API/src/main/java/net/techcable/sonarpet/utils/Versioning.java#L50
