### ISSUE TITLE
1.1.0 snapshots are broken

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#47]
Complete spam in console.

https://gist.githubusercontent.com/andrewkm/c17f2f4486f61b0e49129fc045eacbbf/raw/c80658eb1173c585fac3157ad0d3e8a0f1455284/gistfile1.txt

**Comment by Techcable** [comment]
You should probably downgrade. I'm in the process of more dark voodo to make NMS easier.

**Comment by TechDragon294** [comment]
@Techcable 
You mentioned something about a preprocessor?

**Comment by andrewkm** [comment]
Nope still fucked on Build 26
Cats dont work
Wolve's spam
Etc.

**Comment by Techcable** [comment]
Better described by #63
