### ISSUE TITLE
Not moving / teleporting / spawning / gives damage

### ISSUE THREAD

**Issue by Antal1609** [TechzoneMC/SonarPet#49]
**Endermite**:
Follows you, but if you got to far, he doesn't teleport to you. Also if you go back to him, he doesn't start following you.

**Silverfish**:
Follows you, but if you got to far, he doesn't teleport to you. Also if you go back to him, he doesn't start following you.

**Blaze**:
Doesn't follow / teleport at all.

**Horse**:
Doesn't spawn.

**Magmacube**:
Damage players. And doesn't teleport / follow players.

**Mushroomcow**:
Doesn't spawn.

**Ocelot**:
Doesn't spawn.

**Wolf**:
Doesn't spawn.

**Pigzombie**:
Doesn't spawn.

**Skeleton**:
Burns in sun, doesn't teleport and doesn't follow you.

**Zombie:**:
Burns in sun, doesn't teleport and doesn't follow you.

**Slime**:
Slime pet type is not compatible with this server version. :?

**Witch**:
Doesn't spawn.

**Guardian**:
Spawns, but it will start an server crash.

**Info**:
- All pets that doesn't spawn starts an error log in the console.
- Spigot version: CraftBukkit version git-Spigot-8a048fe-3c19fef (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
- SonarPets version: 1.1.0-snapshot

**Comment by Antal1609** [comment]
Any progress?

**Comment by Techcable** [comment]
Should be fixed as of build 45
