### ISSUE TITLE
Issue with lifesteal plugins

### ISSUE THREAD

**Issue by UltraFaceguy** [TechzoneMC/SonarPet#52]
When pets are immune to damage, players can absorb health from them.

Basically, due to how the damage is cancelled within SonarPet, pets are easily used to endlessly heal players with any plugin that allows you to heal for a percentage of damage dealt damage. Attacking one's own pet, or another pet that shouldn't be attack-able will deal the damage, keep the pet alive, and heal the attacker. When pets shouldn't take damage, the damage event should be set to zero and the event should be cancelled to prevent this.

I used to just checkout a copy of the plugin and change it myself, but eh, maybe other people have the same issue as well. Thanks for your time!

**Comment by Techcable** [comment]
Should be fixed as of [build 45](https://ci.techcable.net/job/SonarPets/45/)
