### ISSUE TITLE
Update to 1.10

### ISSUE THREAD

**Issue by Techcable** [TechzoneMC/SonarPet#55]
Update to minecraft 1.10.
I'll only do it once I finish doing #54, but @cindyker is free to try if she can't wait.

**Comment by TheChampTF** [comment]
[18:11:57 INFO]: [SonarPet] Enabling SonarPet v1.1.0-SNAPSHOT
[18:11:57 INFO]: [EchoPet] [INFO] SonarPet 1.1.0-SNAPSHOT is not compatible with this version of CraftBukkit
[18:11:57 INFO]: [EchoPet] [INFO] Initialisation failed. Please update the plugin.

^Using latest spigot, so find this a little funny (:

**Comment by drekryan** [comment]
@Techcable Whats the status on this issue? I tested updating one of my servers on my network to 1.10 and everything is fine except the issues I have with this plugin on 1.10. This is the only thing holding me back from updating the rest of my servers. I will be watching here for further fixes and checking the CI server often. I noticed its been a few weeks with no further progress for I wanted to check up on this. I understand it takes time but having these issues fixed sooner than later would be good.

**Comment by Techcable** [comment]
I'm working on major code changes.
Also @cindyker already updated to 1.10

**Comment by drekryan** [comment]
Yeah I am using that build but some of the pets are still broken

**Comment by i9hdkill** [comment]
Until it's fixed I suggest you using the other echopet branch. It's updated to 1.10, is not broken and even includes the new mobs.
Working fine on all our 1.10 servers.
@techcable Why not creating a dev branch for testing the major codechanges? Your last changes sadly broke a lot more than it fixed and it's broken since weeks:(

**Comment by drekryan** [comment]
@i9hdkill I am using build 37 from https://ci.techcable.net/job/SonarPets/ but unfortunately this build is still quite broken so I dont know what build you are talking about. For example the Ocelot pet does not render at all.

**Comment by i9hdkill** [comment]
Talking about this one:
http://jenkins.codingforcookies.com/job/EchoPet/
This author didn't change the code, he just updated the plugin. That's the reason why it works.
Techcables major changes he did might be good, but for now, they doesnt work.

**Comment by drekryan** [comment]
Ok thank you! 👍I'll take a look tonight
