### ISSUE TITLE
Horse pets disapear on spawn 1.9.4

### ISSUE THREAD

**Issue by ridalarry** [TechzoneMC/SonarPet#59]
the horses disapear on using /pet horse in the latest dev build

**Comment by HillustratedMike36** [comment]
I can confirm. I tested with and without ViaVersion, and also updating to latest 1.9.4 dev build, but still the same result.

**Comment by afaik4711** [comment]
Same Issue on build #37 on Spigot 1.10

**Comment by Techcable** [comment]
Should be fixed as of build 45
