### ISSUE TITLE
Build #10 Riding Pets

### ISSUE THREAD

**Issue by Internetpilot** [TechzoneMC/SonarPet#6]
Just wanted to let you know that it's working with an extremely minor glitch.  When I switch to a new type of pet, I cannot immediately ride it.  I can mount it, but it won't move anywhere.  However, if I make the pet following me around for even just a few blocks, then I can ride it and control it.  And no console errors, even when the pet won't move. 

Definitely workable, though, and I consider it working.  I just wanted to mention it in case there was something in the code that could be tweaked, but if not I feel this is fine.  

Also, just FYI, pigs glitch badly when trying to ride them, but this seems to also be a vanilla MC 1.9 issue.  

Also, horses are difficult to control when riding, but only when they don't have a saddle on.  This is also normal MC behavior.

Thanks again!

**Comment by Techcable** [comment]
Should be fixed in the latest development builds.
