### ISSUE TITLE
Build 37, tons of pets still broken, severe issues, crashes, more.

### ISSUE THREAD

**Issue by andrewkm** [TechzoneMC/SonarPet#63]
EDIT: Detailed response below.

**Comment by andrewkm** [comment]
Ah screw it lol here I'll test every single pet (have a bit of time now) :) - Will reply with result shortly.

**Comment by andrewkm** [comment]
**Ocelot - no errors, no pet shows up.
Wolf - errors - https://gist.githubusercontent.com/andrewkm/6b4d1cee5808f09d492e8f9283f0ae02/raw/a495f8ae044fe325135acfc137fb6267e460490c/gistfile1.txt**
Pig - Works
Cow - Works
Chicken - Works
Sheep - Works
**Slime - "Pet type is not compatible with this server version"
Mushroomcow - errors - https://gist.githubusercontent.com/andrewkm/38b5e3106583f182857d952d37af76b6/raw/82619aa7beeeb1b3b50b0f452fe0ae8842681193/gistfile1.txt**
Rabbit - Works
Spider - Works
Zombie - Works
Skeleton - Works
Squid - Works
CaveSpider - Works
Skeleton - Works
Creeper - Works
Villager - Works
**Witch - errors - https://gist.githubusercontent.com/andrewkm/5277a764b70b0d338b369ba4d186a54f/raw/9c23caf2ba3aa46d2c78fe5b52d3ac0df3032379/gistfile1.txt
PigZombie - errors - https://gist.githubusercontent.com/andrewkm/118653d64a04f0417ae79b865b551a93/raw/701becc03661171f680121877e5fc7e5a4bfba8c/gistfile1.txt**
MagmaCube - Works
Blaze - Works
Snowman - Works
Endermite - Works
**Silverfish - Semi-works, extremely derpy and spazzes out.
Horse - no errors - no pet shows up
Guardian - endless errors - crashes entire server literally - have to remove from DB after this one, terrible terrible crash - https://gist.githubusercontent.com/andrewkm/6f7975c38b3959cc036d45ecb278f7a3/raw/88c6102782c4755d3d2e5ef282d2facc5532ad5b/gistfile1.txt**
IronGolem - Works
**Enderman - endless errors - crashes entire server literally - have to remove from DB after this one, terrible terrible crash - https://gist.githubusercontent.com/andrewkm/5a4bd28c7841d3b4c93b45e175f98b67/raw/19c3d7c97912f8fa83d68290f3b851b438e79e4a/gistfile1.txt
Wither - Works but is extremely far away and derped out: http://i.imgur.com/5LRi3P6.png**

**Comment by andrewkm** [comment]
@Techcable above is all the issues, basically tons of bugs and completely messed up.

**Comment by i9hdkill** [comment]
Slime pets might be easy to fix.
See here:
https://github.com/TechzoneMC/SonarPet/tree/master/v1_10_R1/src/main/java/com/dsh105/echopet/compat/nms/v1_10_R1/entity
Files are in the wrong folder? (EntitiyPetSlime, EntitityPetSlimeData)

**Comment by TNTUP** [comment]
I got this when the server autosaved itself (bukkit's autosaving) http://paste.md-5.net/ridugojasa.avrasm On Paper 1.10.2 #805, SonarPet Build#37

**Comment by Techcable** [comment]
I'm currently working on major code changes (#54) that will let me easily fix issues across all versions.
So this may take a few days and is effectively blocked on #54 .
Also, thanks for testing all the entities, it'll make fixing them real easy :)

**Comment by andrewkm** [comment]
I've migrated to this: https://github.com/Borlea/EchoPet for now.
All above issues are fixed here.

**Comment by Antal1609** [comment]
Zombie and skelton pets are not working. They will burn in sun light.

**Comment by drekryan** [comment]
Yeah I'm using the EchoPet fork from Borlea as well. I gave up on SonarPet. Still very broken and I needed to get a 1.10 version out asap. It's mostly working for now

**Comment by andrewkm** [comment]
Antal use Borleas fix. It's fully functional.

**Comment by Techcable** [comment]
Wolf error fixed in a249a454d6b4ea51267f553d1892c9812ed4af50

**Comment by Techcable** [comment]
This leaves todo:
- Oceleots
  - [ ] Fix ocelots not showing up (no error)
- Slime
  - [ ] Fix `Pet type is not compatible with this server version`
- Mushroomcow
  - [ ] Fix [ClassCastException](https://gist.githubusercontent.com/andrewkm/38b5e3106583f182857d952d37af76b6/raw/82619aa7beeeb1b3b50b0f452fe0ae8842681193/gistfile1.txt)
- Witch
  - [ ] Fix [ClassCastException](https://gist.githubusercontent.com/andrewkm/5277a764b70b0d338b369ba4d186a54f/raw/9c23caf2ba3aa46d2c78fe5b52d3ac0df3032379/gistfile1.txt)
- ZombiePigman
  - [ ] Fix [StackOverflowError](https://gist.githubusercontent.com/andrewkm/118653d64a04f0417ae79b865b551a93/raw/701becc03661171f680121877e5fc7e5a4bfba8c/gistfile1.txt)
- Silverfish
  - [ ] Fix 'derpyness'
- Horse
  - [ ] Fix not showing up (no errors)
- Guardian
  - [ ] Fix [StackOverflowError](https://gist.githubusercontent.com/andrewkm/6f7975c38b3959cc036d45ecb278f7a3/raw/88c6102782c4755d3d2e5ef282d2facc5532ad5b/gistfile1.txt)
- Enderman
  - [ ] Fix [ClassCastException](https://gist.githubusercontent.com/andrewkm/5a4bd28c7841d3b4c93b45e175f98b67/raw/19c3d7c97912f8fa83d68290f3b851b438e79e4a/gistfile1.txt)
- Wither
  - [ ] Fix ['far away and derped out'](https://i.imgur.com/5LRi3P6.png)

**Comment by andrewkm** [comment]
Fixed for me.
