### ISSUE TITLE
[Bug Spigot 1.9] Mobs never spawn..

### ISSUE THREAD

**Issue by Humanoiidd** [TechzoneMC/SonarPet#64]
Hello,

In my server, your plugin work at 50%, files is good, commands too, but for spawn mobs it's not possible..

Logs : http://pastebin.com/qiCbDpv6

**Comment by Techcable** [comment]
This shouldn't happen on a newer version of 1.9, since [the commit that adds the method](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/21df80186f60e6f13ac9191c9f604a76b1b0b9d5) is before the update to 1.9.2.
Reopen if it does on the last version of 1.9.
