### ISSUE TITLE
SpigotMC - High Performance Minecraft - Error

### ISSUE THREAD

**Issue by Max633** [TechzoneMC/SonarPet#93]
Hi

Your page plugin "You do not have permission to view this page or perform this action."...

Why? oO

Thanks

**Comment by Techcable** [comment]
It's been removed, since I haven't posted an update recently.
Once I finish the 1.11 update, I'll ask them to reopen it.

**Comment by Max633** [comment]
OK nice

**Comment by Max633** [comment]
Can I have a build now? : D
