### ISSUE TITLE
rabbit doesnt walk

### ISSUE THREAD

**Issue by chillerkraft** [TechzoneMC/SonarPet#97]
just teleports to the player. doesn't walk

**Comment by Techcable** [comment]
What version is this?

**Comment by chillerkraft** [comment]
im not sure
how do i check which version i have
did you just recently start the jenkins? i thought i got this plugin from a different page

**Comment by chillerkraft** [comment]
and how odd i got an email notification for this as usual but didnt get a notification on this site for these replies to my issues.. wierd.. i had to go find it myself
