### ISSUE TITLE
/pet hat duplication

### ISSUE THREAD

**Issue by redfrosting** [TechzoneMC/SonarPet#98]
Players can do `/pet <name>` followed by `/pet hat` and repeat this process as many times as they like until it basically lags the server.

https://gyazo.com/a31fec189a3af63832f36bfae0f49ce6

Rather than removing the previous pet they had, it continues to stay on their head.

**Comment by Techcable** [comment]
I have to admit, this is a pretty funny issue. What version of minecraft and SonarPet are you using?

**Comment by redfrosting** [comment]
SonarPet version: 1.1.0-alpha1-release
Spigot version: git-Paper-1103 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
